package com.zit.accounting.dao.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zit.accounting.dao.domain.AccMoneyType;
import com.zit.accounting.dao.domain.AccMoneyTypeExample;

public interface AccMoneyTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    int countByExample(AccMoneyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    int deleteByExample(AccMoneyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer accMoneyTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    int insert(AccMoneyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    int insertSelective(AccMoneyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    List<AccMoneyType> selectByExample(AccMoneyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    AccMoneyType selectByPrimaryKey(Integer accMoneyTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccMoneyType record, @Param("example") AccMoneyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccMoneyType record, @Param("example") AccMoneyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccMoneyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_money_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccMoneyType record);
}