package com.zit.accounting.dao.mapper;


import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.zit.accounting.dao.domain.AccTransaction;
import com.zit.accounting.dao.domain.AccTransactionExample;

public interface AccTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    int countByExample(AccTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    int deleteByExample(AccTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer accTransactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    int insert(AccTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    int insertSelective(AccTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    List<AccTransaction> selectByExample(AccTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    AccTransaction selectByPrimaryKey(Integer accTransactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccTransaction record, @Param("example") AccTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccTransaction record, @Param("example") AccTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_transaction
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccTransaction record);
}