package com.zit.accounting.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.zit.accounting.dao.domain.AccUser;
import com.zit.accounting.dao.domain.AccUserExample;

public interface AccUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    int countByExample(AccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    int deleteByExample(AccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer accUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    int insert(AccUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    int insertSelective(AccUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    List<AccUser> selectByExample(AccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    AccUser selectByPrimaryKey(Integer accUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccUser record, @Param("example") AccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccUser record, @Param("example") AccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccUser record);
}