package com.zit.accounting.dao.domain;


public class AccConsumeType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_consume_type.ACC_CONSUME_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer accConsumeTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_consume_type.TYPE_CODE
     *
     * @mbggenerated
     */
    private Integer typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_consume_type.TYPE_NAME
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_consume_type.TYPE_DESC
     *
     * @mbggenerated
     */
    private String typeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_consume_type.ACC_CONSUME_TYPE_ID
     *
     * @return the value of acc_consume_type.ACC_CONSUME_TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getAccConsumeTypeId() {
        return accConsumeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_consume_type.ACC_CONSUME_TYPE_ID
     *
     * @param accConsumeTypeId the value for acc_consume_type.ACC_CONSUME_TYPE_ID
     *
     * @mbggenerated
     */
    public void setAccConsumeTypeId(Integer accConsumeTypeId) {
        this.accConsumeTypeId = accConsumeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_consume_type.TYPE_CODE
     *
     * @return the value of acc_consume_type.TYPE_CODE
     *
     * @mbggenerated
     */
    public Integer getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_consume_type.TYPE_CODE
     *
     * @param typeCode the value for acc_consume_type.TYPE_CODE
     *
     * @mbggenerated
     */
    public void setTypeCode(Integer typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_consume_type.TYPE_NAME
     *
     * @return the value of acc_consume_type.TYPE_NAME
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_consume_type.TYPE_NAME
     *
     * @param typeName the value for acc_consume_type.TYPE_NAME
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_consume_type.TYPE_DESC
     *
     * @return the value of acc_consume_type.TYPE_DESC
     *
     * @mbggenerated
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_consume_type.TYPE_DESC
     *
     * @param typeDesc the value for acc_consume_type.TYPE_DESC
     *
     * @mbggenerated
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }
}