package com.zit.accounting.dao.domain;

public class AccUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.ACC_USER_ID
     *
     * @mbggenerated
     */
    private Integer accUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.USER_ID_CARD_NO
     *
     * @mbggenerated
     */
    private String userIdCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.GENDER
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.AGE
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.PHOTO
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.ALIAS
     *
     * @mbggenerated
     */
    private String alias;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.ACC_USER_ID
     *
     * @return the value of acc_user.ACC_USER_ID
     *
     * @mbggenerated
     */
    public Integer getAccUserId() {
        return accUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.ACC_USER_ID
     *
     * @param accUserId the value for acc_user.ACC_USER_ID
     *
     * @mbggenerated
     */
    public void setAccUserId(Integer accUserId) {
        this.accUserId = accUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.USER_NAME
     *
     * @return the value of acc_user.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.USER_NAME
     *
     * @param userName the value for acc_user.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.USER_ID_CARD_NO
     *
     * @return the value of acc_user.USER_ID_CARD_NO
     *
     * @mbggenerated
     */
    public String getUserIdCardNo() {
        return userIdCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.USER_ID_CARD_NO
     *
     * @param userIdCardNo the value for acc_user.USER_ID_CARD_NO
     *
     * @mbggenerated
     */
    public void setUserIdCardNo(String userIdCardNo) {
        this.userIdCardNo = userIdCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.GENDER
     *
     * @return the value of acc_user.GENDER
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.GENDER
     *
     * @param gender the value for acc_user.GENDER
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.AGE
     *
     * @return the value of acc_user.AGE
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.AGE
     *
     * @param age the value for acc_user.AGE
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.PHONE
     *
     * @return the value of acc_user.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.PHONE
     *
     * @param phone the value for acc_user.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.ADDRESS
     *
     * @return the value of acc_user.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.ADDRESS
     *
     * @param address the value for acc_user.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.PHOTO
     *
     * @return the value of acc_user.PHOTO
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.PHOTO
     *
     * @param photo the value for acc_user.PHOTO
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.ALIAS
     *
     * @return the value of acc_user.ALIAS
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.ALIAS
     *
     * @param alias the value for acc_user.ALIAS
     *
     * @mbggenerated
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }
}